import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export const aiCompanies = [
  {
    name: "OpenAI",
    slug: "openai",
    logo: "https://logo.clearbit.com/openai.com",
    shortDescription: "AI research and deployment company building advanced artificial intelligence systems.",
    description:
      "OpenAI develops artificial intelligence systems and research focused on creating useful and increasingly capable AI.",
    industry: "Artificial Intelligence",
    categories: ["AI Research", "Foundation Models", "Generative AI"],
    technologies: ["Large Language Models", "Generative AI", "Multimodal AI"],
    foundedYear: 2015,
    location: "San Francisco, USA",
    companyType: "AI Research Lab",
    stage: "Private",
    website: "https://openai.com",
    linkedin: "https://www.linkedin.com/company/openai",
    twitter: "https://x.com/OpenAI",
    github: "https://github.com/openai",
    featured: true,
  },

  {
    name: "Anthropic",
    slug: "anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    shortDescription: "AI research company focused on reliable, interpretable, and steerable AI.",
    description:
      "Anthropic researches and develops AI systems with an emphasis on reliability, safety, and useful real-world applications.",
    industry: "Artificial Intelligence",
    categories: ["AI Research", "Foundation Models", "Generative AI"],
    technologies: ["Large Language Models", "AI Safety", "Generative AI"],
    foundedYear: 2021,
    location: "San Francisco, USA",
    companyType: "AI Research Lab",
    stage: "Private",
    website: "https://www.anthropic.com",
    linkedin: "https://www.linkedin.com/company/anthropicresearch",
    twitter: "https://x.com/AnthropicAI",
    github: null,
    featured: true,
  },

  {
    name: "Google DeepMind",
    slug: "google-deepmind",
    logo: "https://logo.clearbit.com/deepmind.google",
    shortDescription: "AI research organization developing advanced systems across science and computing.",
    description:
      "Google DeepMind combines machine learning research with scientific discovery and large-scale AI applications.",
    industry: "Artificial Intelligence",
    categories: ["AI Research", "Foundation Models", "Healthcare AI"],
    technologies: ["Deep Learning", "Reinforcement Learning", "Generative AI"],
    foundedYear: 2010,
    location: "London, UK",
    companyType: "AI Research Organization",
    stage: "Private",
    website: "https://deepmind.google",
    linkedin: "https://www.linkedin.com/company/google-deepmind",
    twitter: "https://x.com/GoogleDeepMind",
    github: "https://github.com/google-deepmind",
    featured: true,
  },

  {
    name: "Mistral AI",
    slug: "mistral-ai",
    logo: "https://logo.clearbit.com/mistral.ai",
    shortDescription: "AI company developing efficient and open-weight foundation models.",
    description:
      "Mistral AI develops generative AI models designed for efficient deployment across consumer and enterprise applications.",
    industry: "Artificial Intelligence",
    categories: ["Foundation Models", "Generative AI", "AI Research"],
    technologies: ["Large Language Models", "Open Models", "Generative AI"],
    foundedYear: 2023,
    location: "Paris, France",
    companyType: "AI Company",
    stage: "Private",
    website: "https://mistral.ai",
    linkedin: "https://www.linkedin.com/company/mistralai",
    twitter: "https://x.com/MistralAI",
    github: "https://github.com/mistralai",
    featured: true,
  },

  {
    name: "Cohere",
    slug: "cohere",
    logo: "https://logo.clearbit.com/cohere.com",
    shortDescription: "Enterprise AI company building language models and AI infrastructure.",
    description:
      "Cohere develops language models and AI services designed for enterprise search, generation, and automation.",
    industry: "Enterprise AI",
    categories: ["Foundation Models", "Enterprise AI", "Generative AI"],
    technologies: ["LLMs", "Natural Language Processing", "RAG"],
    foundedYear: 2019,
    location: "Toronto, Canada",
    companyType: "AI Company",
    stage: "Private",
    website: "https://cohere.com",
    linkedin: "https://www.linkedin.com/company/cohere-ai",
    twitter: "https://x.com/cohere",
    github: "https://github.com/cohere-ai",
    featured: false,
  },

  {
    name: "xAI",
    slug: "xai",
    logo: "https://logo.clearbit.com/x.ai",
    shortDescription: "AI company developing intelligent systems and large language models.",
    description:
      "xAI develops AI systems and foundation models with a focus on advanced reasoning and general-purpose intelligence.",
    industry: "Artificial Intelligence",
    categories: ["AI Research", "Foundation Models", "Generative AI"],
    technologies: ["Large Language Models", "Generative AI", "Reasoning AI"],
    foundedYear: 2023,
    location: "Palo Alto, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://x.ai",
    linkedin: null,
    twitter: "https://x.com/xai",
    github: null,
    featured: true,
  },

  {
    name: "Hugging Face",
    slug: "hugging-face",
    logo: "https://logo.clearbit.com/huggingface.co",
    shortDescription: "Open AI platform providing models, datasets, and machine learning tools.",
    description:
      "Hugging Face provides an open ecosystem where developers and researchers can share, discover, and deploy machine learning models and datasets.",
    industry: "AI Developer Tools",
    categories: ["AI Infrastructure", "Developer Tools", "Foundation Models"],
    technologies: ["Machine Learning", "Open Models", "NLP"],
    foundedYear: 2016,
    location: "New York, USA",
    companyType: "AI Platform",
    stage: "Private",
    website: "https://huggingface.co",
    linkedin: "https://www.linkedin.com/company/huggingface",
    twitter: "https://x.com/huggingface",
    github: "https://github.com/huggingface",
    featured: true,
  },

  {
    name: "Perplexity",
    slug: "perplexity",
    logo: "https://logo.clearbit.com/perplexity.ai",
    shortDescription: "AI-powered search and answer engine for research and information discovery.",
    description:
      "Perplexity combines search with generative AI to provide conversational answers supported by web information.",
    industry: "AI Search",
    categories: ["AI Search", "Generative AI", "AI Assistants"],
    technologies: ["LLMs", "Search", "RAG"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://www.perplexity.ai",
    linkedin: "https://www.linkedin.com/company/perplexity-ai",
    twitter: "https://x.com/perplexity_ai",
    github: null,
    featured: true,
  },

  {
    name: "Scale AI",
    slug: "scale-ai",
    logo: "https://logo.clearbit.com/scale.com",
    shortDescription: "AI infrastructure company providing data and evaluation systems for machine learning.",
    description:
      "Scale AI builds infrastructure and data services that help organizations develop, evaluate, and deploy AI systems.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "Computer Vision", "Enterprise AI"],
    technologies: ["Data Labeling", "Machine Learning", "AI Evaluation"],
    foundedYear: 2016,
    location: "San Francisco, USA",
    companyType: "AI Infrastructure",
    stage: "Private",
    website: "https://scale.com",
    linkedin: "https://www.linkedin.com/company/scaleai",
    twitter: "https://x.com/scale_ai",
    github: null,
    featured: false,
  },

  {
    name: "Runway",
    slug: "runway",
    logo: "https://logo.clearbit.com/runwayml.com",
    shortDescription: "Generative AI company creating tools for video and creative production.",
    description:
      "Runway develops generative AI technologies that enable creators to produce and transform video and visual content.",
    industry: "Generative Media",
    categories: ["Generative AI", "Video AI", "Creative AI"],
    technologies: ["Text-to-Video", "Computer Vision", "Generative AI"],
    foundedYear: 2018,
    location: "New York, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://runwayml.com",
    linkedin: "https://www.linkedin.com/company/runwayml",
    twitter: "https://x.com/runwayml",
    github: null,
    featured: true,
  },

  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    logo: "https://logo.clearbit.com/elevenlabs.io",
    shortDescription: "AI voice platform specializing in speech synthesis and voice technology.",
    description:
      "ElevenLabs develops AI voice technology for speech generation, dubbing, narration, and conversational applications.",
    industry: "Voice AI",
    categories: ["Voice & Audio", "Generative AI", "AI Developer Tools"],
    technologies: ["Text-to-Speech", "Voice Cloning", "Speech AI"],
    foundedYear: 2022,
    location: "New York, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://elevenlabs.io",
    linkedin: "https://www.linkedin.com/company/elevenlabsio",
    twitter: "https://x.com/elevenlabsio",
    github: "https://github.com/elevenlabs",
    featured: true,
  },

  {
    name: "Midjourney",
    slug: "midjourney",
    logo: "https://logo.clearbit.com/midjourney.com",
    shortDescription: "Independent research lab developing generative AI for visual creativity.",
    description:
      "Midjourney develops generative models that enable users to create visual artwork and images from natural language prompts.",
    industry: "Generative Media",
    categories: ["Image Generation", "Generative AI", "Creative AI"],
    technologies: ["Text-to-Image", "Generative Models", "Computer Vision"],
    foundedYear: 2021,
    location: "San Francisco, USA",
    companyType: "Research Lab",
    stage: "Private",
    website: "https://www.midjourney.com",
    linkedin: null,
    twitter: "https://x.com/midjourney",
    github: null,
    featured: true,
  },

  {
    name: "Stability AI",
    slug: "stability-ai",
    logo: "https://logo.clearbit.com/stability.ai",
    shortDescription: "AI company developing open generative models for images, video, audio, and 3D.",
    description:
      "Stability AI develops generative models and creative AI technologies across multiple media formats.",
    industry: "Generative AI",
    categories: ["Image Generation", "Video AI", "Generative AI"],
    technologies: ["Diffusion Models", "Text-to-Image", "Generative AI"],
    foundedYear: 2019,
    location: "London, UK",
    companyType: "AI Company",
    stage: "Private",
    website: "https://stability.ai",
    linkedin: "https://www.linkedin.com/company/stability-ai",
    twitter: "https://x.com/StabilityAI",
    github: "https://github.com/Stability-AI",
    featured: false,
  },

  {
    name: "Character AI",
    slug: "character-ai",
    logo: "https://logo.clearbit.com/character.ai",
    shortDescription: "Conversational AI platform for creating and interacting with AI characters.",
    description:
      "Character AI develops conversational systems that allow users to interact with customizable AI personalities and characters.",
    industry: "AI Assistants",
    categories: ["AI Agents", "Generative AI", "Conversational AI"],
    technologies: ["LLMs", "Conversational AI", "Generative AI"],
    foundedYear: 2021,
    location: "Menlo Park, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://character.ai",
    linkedin: "https://www.linkedin.com/company/character-ai",
    twitter: "https://x.com/character_ai",
    github: null,
    featured: false,
  },

  {
    name: "Databricks",
    slug: "databricks",
    logo: "https://logo.clearbit.com/databricks.com",
    shortDescription: "Data and AI platform helping organizations build and operate machine learning systems.",
    description:
      "Databricks provides a unified platform for data engineering, analytics, machine learning, and generative AI.",
    industry: "Enterprise AI",
    categories: ["AI Infrastructure", "Enterprise AI", "Developer Tools"],
    technologies: ["Machine Learning", "Data Engineering", "LLMs"],
    foundedYear: 2013,
    location: "San Francisco, USA",
    companyType: "AI Platform",
    stage: "Private",
    website: "https://www.databricks.com",
    linkedin: "https://www.linkedin.com/company/databricks",
    twitter: "https://x.com/databricks",
    github: "https://github.com/databricks",
    featured: false,
  },

  {
    name: "Together AI",
    slug: "together-ai",
    logo: "https://logo.clearbit.com/together.ai",
    shortDescription: "AI cloud platform for developing, training, and deploying open models.",
    description:
      "Together AI provides infrastructure and services for organizations building applications with open-source and open-weight AI models.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "Foundation Models", "Developer Tools"],
    technologies: ["LLMs", "GPU Computing", "Model Training"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Infrastructure",
    stage: "Private",
    website: "https://www.together.ai",
    linkedin: "https://www.linkedin.com/company/togethercomputer",
    twitter: "https://x.com/togethercompute",
    github: "https://github.com/togethercomputer",
    featured: false,
  },

  {
    name: "Replicate",
    slug: "replicate",
    logo: "https://logo.clearbit.com/replicate.com",
    shortDescription: "Platform that makes it easier to run and deploy machine learning models.",
    description:
      "Replicate provides APIs and infrastructure for developers to run machine learning models without managing complex infrastructure.",
    industry: "AI Developer Tools",
    categories: ["Developer Tools", "AI Infrastructure", "Generative AI"],
    technologies: ["Model APIs", "Machine Learning", "GPU Computing"],
    foundedYear: 2019,
    location: "San Francisco, USA",
    companyType: "AI Platform",
    stage: "Private",
    website: "https://replicate.com",
    linkedin: "https://www.linkedin.com/company/replicate-labs",
    twitter: "https://x.com/repaborate",
    github: "https://github.com/replicate",
    featured: false,
  },

  {
    name: "Groq",
    slug: "groq",
    logo: "https://logo.clearbit.com/groq.com",
    shortDescription: "AI infrastructure company developing specialized hardware and inference systems.",
    description:
      "Groq develops specialized computing technology designed to deliver high-performance AI inference.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "AI Hardware", "Developer Tools"],
    technologies: ["AI Chips", "Inference", "GPU Alternatives"],
    foundedYear: 2016,
    location: "Mountain View, USA",
    companyType: "AI Hardware Company",
    stage: "Private",
    website: "https://groq.com",
    linkedin: "https://www.linkedin.com/company/groq",
    twitter: "https://x.com/GroqInc",
    github: null,
    featured: false,
  },

  {
    name: "CoreWeave",
    slug: "coreweave",
    logo: "https://logo.clearbit.com/coreweave.com",
    shortDescription: "Cloud infrastructure provider specializing in accelerated computing for AI.",
    description:
      "CoreWeave provides cloud infrastructure optimized for AI workloads, model training, and high-performance computing.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "Cloud AI", "AI Hardware"],
    technologies: ["GPU Computing", "Cloud Computing", "Model Training"],
    foundedYear: 2017,
    location: "Roseland, USA",
    companyType: "AI Cloud Provider",
    stage: "Public",
    website: "https://www.coreweave.com",
    linkedin: "https://www.linkedin.com/company/coreweave",
    twitter: "https://x.com/CoreWeave",
    github: null,
    featured: false,
  },

  {
    name: "NVIDIA",
    slug: "nvidia",
    logo: "https://logo.clearbit.com/nvidia.com",
    shortDescription: "Computing company powering AI workloads through accelerated hardware and software.",
    description:
      "NVIDIA develops accelerated computing platforms, GPUs, software, and infrastructure used extensively for modern AI workloads.",
    industry: "AI Hardware",
    categories: ["AI Infrastructure", "AI Hardware", "Developer Tools"],
    technologies: ["GPUs", "CUDA", "Deep Learning"],
    foundedYear: 1993,
    location: "Santa Clara, USA",
    companyType: "Technology Company",
    stage: "Public",
    website: "https://www.nvidia.com",
    linkedin: "https://www.linkedin.com/company/nvidia",
    twitter: "https://x.com/nvidia",
    github: "https://github.com/NVIDIA",
    featured: true,
  },

  {
    name: "Cursor",
    slug: "cursor",
    logo: "https://logo.clearbit.com/cursor.com",
    shortDescription: "AI-powered code editor designed to help developers write and understand software.",
    description:
      "Cursor is an AI-first development environment that integrates coding assistance directly into the software development workflow.",
    industry: "Developer Tools",
    categories: ["Developer Tools", "AI Coding", "AI Assistants"],
    technologies: ["LLMs", "Code Generation", "AI Agents"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://www.cursor.com",
    linkedin: "https://www.linkedin.com/company/cursorai",
    twitter: "https://x.com/cursor_ai",
    github: null,
    featured: true,
  },

  {
    name: "Replit",
    slug: "replit",
    logo: "https://logo.clearbit.com/replit.com",
    shortDescription: "Online development platform combining collaborative coding with AI assistance.",
    description:
      "Replit provides a browser-based development environment with AI-powered coding and application-building capabilities.",
    industry: "Developer Tools",
    categories: ["Developer Tools", "AI Coding", "AI Agents"],
    technologies: ["Code Generation", "AI Agents", "Cloud Development"],
    foundedYear: 2016,
    location: "Foster City, USA",
    companyType: "Technology Company",
    stage: "Private",
    website: "https://replit.com",
    linkedin: "https://www.linkedin.com/company/replit",
    twitter: "https://x.com/Replit",
    github: "https://github.com/replit",
    featured: false,
  },

  {
    name: "AssemblyAI",
    slug: "assemblyai",
    logo: "https://logo.clearbit.com/assemblyai.com",
    shortDescription: "AI platform providing speech recognition and audio intelligence APIs.",
    description:
      "AssemblyAI develops speech AI models and APIs for transcription, audio understanding, and voice-based applications.",
    industry: "Voice AI",
    categories: ["Voice & Audio", "Developer Tools", "Generative AI"],
    technologies: ["Speech Recognition", "NLP", "Audio AI"],
    foundedYear: 2017,
    location: "San Francisco, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://www.assemblyai.com",
    linkedin: "https://www.linkedin.com/company/assemblyai",
    twitter: "https://x.com/AssemblyAI",
    github: null,
    featured: false,
  },

  {
    name: "Deepgram",
    slug: "deepgram",
    logo: "https://logo.clearbit.com/deepgram.com",
    shortDescription: "Speech AI company building real-time voice intelligence technology.",
    description:
      "Deepgram provides speech recognition and voice AI infrastructure for applications requiring real-time audio understanding.",
    industry: "Voice AI",
    categories: ["Voice & Audio", "Developer Tools", "Enterprise AI"],
    technologies: ["Speech-to-Text", "Speech AI", "NLP"],
    foundedYear: 2015,
    location: "San Francisco, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://deepgram.com",
    linkedin: "https://www.linkedin.com/company/deepgram",
    twitter: "https://x.com/deepgramAI",
    github: null,
    featured: false,
  },

  {
    name: "Pika",
    slug: "pika",
    logo: "https://logo.clearbit.com/pika.art",
    shortDescription: "Generative AI platform for creating and editing video content.",
    description:
      "Pika develops generative video technologies that help users create and transform visual content with AI.",
    industry: "Generative Media",
    categories: ["Video AI", "Generative AI", "Creative AI"],
    technologies: ["Text-to-Video", "Video Generation", "Computer Vision"],
    foundedYear: 2023,
    location: "Palo Alto, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://pika.art",
    linkedin: null,
    twitter: "https://x.com/pika_labs",
    github: null,
    featured: false,
  },

  {
    name: "Luma AI",
    slug: "luma-ai",
    logo: "https://logo.clearbit.com/lumalabs.ai",
    shortDescription: "AI company developing generative models for video and 3D content.",
    description:
      "Luma AI builds generative AI technologies for creating and manipulating video, images, and three-dimensional content.",
    industry: "Generative Media",
    categories: ["Video AI", "3D AI", "Generative AI"],
    technologies: ["Video Generation", "3D Generation", "Computer Vision"],
    foundedYear: 2021,
    location: "Palo Alto, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://lumalabs.ai",
    linkedin: "https://www.linkedin.com/company/luma-ai",
    twitter: "https://x.com/LumaLabsAI",
    github: null,
    featured: false,
  },

  {
    name: "Synthesia",
    slug: "synthesia",
    logo: "https://logo.clearbit.com/synthesia.io",
    shortDescription: "AI video platform for creating professional videos with digital presenters.",
    description:
      "Synthesia provides AI video creation tools that allow organizations to produce training, communication, and marketing content.",
    industry: "Generative Media",
    categories: ["Video AI", "Enterprise AI", "Generative AI"],
    technologies: ["AI Avatars", "Text-to-Video", "Speech AI"],
    foundedYear: 2017,
    location: "London, UK",
    companyType: "AI Company",
    stage: "Private",
    website: "https://www.synthesia.io",
    linkedin: "https://www.linkedin.com/company/synthesia-technologies",
    twitter: "https://x.com/synthesiaIO",
    github: null,
    featured: false,
  },

  {
    name: "Harvey",
    slug: "harvey",
    logo: "https://logo.clearbit.com/harvey.ai",
    shortDescription: "Generative AI platform designed for professional legal workflows.",
    description:
      "Harvey develops AI-powered tools that assist legal professionals with research, drafting, analysis, and workflow automation.",
    industry: "Legal AI",
    categories: ["Enterprise AI", "AI Agents", "Generative AI"],
    technologies: ["LLMs", "Document AI", "AI Agents"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://www.harvey.ai",
    linkedin: "https://www.linkedin.com/company/harvey-ai",
    twitter: "https://x.com/harvey_ai",
    github: null,
    featured: false,
  },

  {
    name: "Glean",
    slug: "glean",
    logo: "https://logo.clearbit.com/glean.com",
    shortDescription: "Enterprise AI platform for workplace search and knowledge discovery.",
    description:
      "Glean develops enterprise AI technology that helps employees search organizational knowledge and automate workplace tasks.",
    industry: "Enterprise AI",
    categories: ["Enterprise AI", "AI Search", "AI Agents"],
    technologies: ["Enterprise Search", "RAG", "AI Agents"],
    foundedYear: 2019,
    location: "Palo Alto, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://www.glean.com",
    linkedin: "https://www.linkedin.com/company/gleanwork",
    twitter: "https://x.com/gleanwork",
    github: null,
    featured: false,
  },

  {
    name: "Writer",
    slug: "writer",
    logo: "https://logo.clearbit.com/writer.com",
    shortDescription: "Enterprise generative AI platform for business content and workflows.",
    description:
      "Writer provides enterprise AI tools for content generation, knowledge management, and automated business workflows.",
    industry: "Enterprise AI",
    categories: ["Enterprise AI", "Generative AI", "AI Agents"],
    technologies: ["LLMs", "RAG", "AI Agents"],
    foundedYear: 2020,
    location: "San Francisco, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://writer.com",
    linkedin: "https://www.linkedin.com/company/writer-ai",
    twitter: "https://x.com/getwriter",
    github: null,
    featured: false,
  },

  {
    name: "C3 AI",
    slug: "c3-ai",
    logo: "https://logo.clearbit.com/c3.ai",
    shortDescription: "Enterprise AI software company serving industrial and business applications.",
    description:
      "C3 AI develops enterprise AI applications and platforms for industries including energy, manufacturing, defense, and financial services.",
    industry: "Enterprise AI",
    categories: ["Enterprise AI", "Predictive AI", "AI Infrastructure"],
    technologies: ["Machine Learning", "Predictive Analytics", "Generative AI"],
    foundedYear: 2009,
    location: "Redwood City, USA",
    companyType: "Technology Company",
    stage: "Public",
    website: "https://c3.ai",
    linkedin: "https://www.linkedin.com/company/c3-ai",
    twitter: "https://x.com/C3_AI",
    github: null,
    featured: false,
  },

  {
    name: "Dataiku",
    slug: "dataiku",
    logo: "https://logo.clearbit.com/dataiku.com",
    shortDescription: "Enterprise platform for analytics, machine learning, and generative AI.",
    description:
      "Dataiku provides an enterprise AI platform that helps organizations develop, govern, and deploy data and AI projects.",
    industry: "Enterprise AI",
    categories: ["Enterprise AI", "Machine Learning", "AI Infrastructure"],
    technologies: ["Machine Learning", "Data Science", "Generative AI"],
    foundedYear: 2013,
    location: "New York, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://www.dataiku.com",
    linkedin: "https://www.linkedin.com/company/dataiku",
    twitter: "https://x.com/dataiku",
    github: null,
    featured: false,
  },

  {
    name: "Tempus",
    slug: "tempus",
    logo: "https://logo.clearbit.com/tempus.com",
    shortDescription: "Healthcare technology company applying AI and data to precision medicine.",
    description:
      "Tempus uses AI and large-scale healthcare data to support precision medicine, diagnostics, and clinical decision-making.",
    industry: "Healthcare AI",
    categories: ["Healthcare AI", "Machine Learning", "Enterprise AI"],
    technologies: ["Machine Learning", "Healthcare Analytics", "Genomics"],
    foundedYear: 2015,
    location: "Chicago, USA",
    companyType: "Healthcare Technology",
    stage: "Public",
    website: "https://www.tempus.com",
    linkedin: "https://www.linkedin.com/company/tempus-labs",
    twitter: "https://x.com/TempusAI",
    github: null,
    featured: false,
  },

  {
    name: "Abridge",
    slug: "abridge",
    logo: "https://logo.clearbit.com/abridge.com",
    shortDescription: "Healthcare AI company creating intelligent clinical documentation tools.",
    description:
      "Abridge develops AI technology that helps clinicians automatically transform conversations into useful clinical documentation.",
    industry: "Healthcare AI",
    categories: ["Healthcare AI", "Voice & Audio", "Enterprise AI"],
    technologies: ["Speech Recognition", "NLP", "Generative AI"],
    foundedYear: 2018,
    location: "Pittsburgh, USA",
    companyType: "Healthcare AI Company",
    stage: "Private",
    website: "https://www.abridge.com",
    linkedin: "https://www.linkedin.com/company/abridge",
    twitter: "https://x.com/abridgeHQ",
    github: null,
    featured: false,
  },

  {
    name: "Insitro",
    slug: "insitro",
    logo: "https://logo.clearbit.com/insitro.com",
    shortDescription: "AI-driven drug discovery company combining machine learning and biology.",
    description:
      "Insitro applies machine learning and biological data to improve the discovery and development of new medicines.",
    industry: "Healthcare AI",
    categories: ["Healthcare AI", "AI Research", "Machine Learning"],
    technologies: ["Machine Learning", "Drug Discovery", "Biological AI"],
    foundedYear: 2018,
    location: "San Francisco, USA",
    companyType: "Biotechnology Company",
    stage: "Private",
    website: "https://insitro.com",
    linkedin: "https://www.linkedin.com/company/insitro",
    twitter: "https://x.com/insitro",
    github: null,
    featured: false,
  },

  {
    name: "PathAI",
    slug: "pathai",
    logo: "https://logo.clearbit.com/pathai.com",
    shortDescription: "AI company developing machine learning solutions for pathology and healthcare.",
    description:
      "PathAI develops AI-powered pathology technology designed to improve disease diagnosis, research, and drug development.",
    industry: "Healthcare AI",
    categories: ["Healthcare AI", "Computer Vision", "AI Research"],
    technologies: ["Computer Vision", "Medical Imaging", "Machine Learning"],
    foundedYear: 2016,
    location: "Boston, USA",
    companyType: "Healthcare AI Company",
    stage: "Private",
    website: "https://www.pathai.com",
    linkedin: "https://www.linkedin.com/company/pathai",
    twitter: "https://x.com/PathAI",
    github: null,
    featured: false,
  },

  {
    name: "Figure AI",
    slug: "figure-ai",
    logo: "https://logo.clearbit.com/figure.ai",
    shortDescription: "Robotics company developing humanoid robots powered by AI.",
    description:
      "Figure AI develops humanoid robots designed to operate in environments built for people and perform useful physical tasks.",
    industry: "Robotics",
    categories: ["Robotics", "Physical AI", "AI Research"],
    technologies: ["Computer Vision", "Robotics", "Embodied AI"],
    foundedYear: 2022,
    location: "Sunnyvale, USA",
    companyType: "Robotics Company",
    stage: "Private",
    website: "https://www.figure.ai",
    linkedin: "https://www.linkedin.com/company/figure-ai",
    twitter: "https://x.com/Figure_robot",
    github: null,
    featured: true,
  },

  {
    name: "Agility Robotics",
    slug: "agility-robotics",
    logo: "https://logo.clearbit.com/agilityrobotics.com",
    shortDescription: "Robotics company developing humanoid robots for commercial environments.",
    description:
      "Agility Robotics develops mobile humanoid robots designed to work alongside people in logistics and other real-world environments.",
    industry: "Robotics",
    categories: ["Robotics", "Physical AI", "Computer Vision"],
    technologies: ["Humanoid Robotics", "Computer Vision", "Embodied AI"],
    foundedYear: 2015,
    location: "Corvallis, USA",
    companyType: "Robotics Company",
    stage: "Private",
    website: "https://agilityrobotics.com",
    linkedin: "https://www.linkedin.com/company/agilityrobotics",
    twitter: "https://x.com/agilityrobotics",
    github: null,
    featured: false,
  },

  {
    name: "1X",
    slug: "1x",
    logo: "https://logo.clearbit.com/1x.tech",
    shortDescription: "Robotics company developing humanoid robots for physical-world tasks.",
    description:
      "1X builds AI-powered humanoid robots designed to perform practical tasks in homes and workplaces.",
    industry: "Robotics",
    categories: ["Robotics", "Physical AI", "AI Research"],
    technologies: ["Humanoid Robotics", "Embodied AI", "Computer Vision"],
    foundedYear: 2014,
    location: "Oslo, Norway",
    companyType: "Robotics Company",
    stage: "Private",
    website: "https://www.1x.tech",
    linkedin: "https://www.linkedin.com/company/1x-technologies",
    twitter: "https://x.com/1x_tech",
    github: null,
    featured: false,
  },

  {
    name: "Physical Intelligence",
    slug: "physical-intelligence",
    logo: "https://logo.clearbit.com/physicalintelligence.company",
    shortDescription: "AI research company developing general-purpose models for robots.",
    description:
      "Physical Intelligence develops machine learning systems intended to help robots perform a wide range of physical tasks.",
    industry: "Robotics",
    categories: ["Robotics", "Physical AI", "AI Research"],
    technologies: ["Embodied AI", "Robot Learning", "Multimodal AI"],
    foundedYear: 2024,
    location: "San Francisco, USA",
    companyType: "AI Research Company",
    stage: "Private",
    website: "https://www.physicalintelligence.company",
    linkedin: "https://www.linkedin.com/company/physical-intelligence",
    twitter: null,
    github: null,
    featured: false,
  },

  {
    name: "Waymo",
    slug: "waymo",
    logo: "https://logo.clearbit.com/waymo.com",
    shortDescription: "Autonomous driving company developing AI-powered transportation systems.",
    description:
      "Waymo develops autonomous driving technology that combines machine learning, sensors, mapping, and robotics.",
    industry: "Autonomous Vehicles",
    categories: ["Robotics", "Computer Vision", "Physical AI"],
    technologies: ["Autonomous Driving", "Computer Vision", "Machine Learning"],
    foundedYear: 2009,
    location: "Mountain View, USA",
    companyType: "Technology Company",
    stage: "Private",
    website: "https://waymo.com",
    linkedin: "https://www.linkedin.com/company/waymo",
    twitter: "https://x.com/waymo",
    github: null,
    featured: true,
  },

  {
    name: "Skild AI",
    slug: "skild-ai",
    logo: "https://logo.clearbit.com/skild.ai",
    shortDescription: "AI robotics company developing general-purpose intelligence for robots.",
    description:
      "Skild AI develops foundation models intended to enable robots to learn and perform a broad range of physical tasks.",
    industry: "Robotics",
    categories: ["Robotics", "Physical AI", "Foundation Models"],
    technologies: ["Robot Learning", "Embodied AI", "Foundation Models"],
    foundedYear: 2023,
    location: "Pittsburgh, USA",
    companyType: "AI Robotics Company",
    stage: "Private",
    website: "https://www.skild.ai",
    linkedin: "https://www.linkedin.com/company/skild-ai",
    twitter: null,
    github: null,
    featured: false,
  },

  {
    name: "Landing AI",
    slug: "landing-ai",
    logo: "https://logo.clearbit.com/landing.ai",
    shortDescription: "Computer vision company helping businesses build visual AI applications.",
    description:
      "Landing AI develops computer vision tools that enable organizations to create and deploy custom visual inspection systems.",
    industry: "Computer Vision",
    categories: ["Computer Vision", "Developer Tools", "Enterprise AI"],
    technologies: ["Computer Vision", "Visual Inspection", "Machine Learning"],
    foundedYear: 2017,
    location: "Palo Alto, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://landing.ai",
    linkedin: "https://www.linkedin.com/company/landing-ai",
    twitter: "https://x.com/LandingAI",
    github: "https://github.com/landing-ai",
    featured: false,
  },

  {
    name: "Roboflow",
    slug: "roboflow",
    logo: "https://logo.clearbit.com/roboflow.com",
    shortDescription: "Computer vision platform for building and deploying custom vision models.",
    description:
      "Roboflow provides tools for collecting, labeling, training, evaluating, and deploying computer vision models.",
    industry: "Computer Vision",
    categories: ["Computer Vision", "Developer Tools", "AI Infrastructure"],
    technologies: ["Object Detection", "Computer Vision", "Model Training"],
    foundedYear: 2019,
    location: "Des Moines, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://roboflow.com",
    linkedin: "https://www.linkedin.com/company/roboflow",
    twitter: "https://x.com/roboflow",
    github: "https://github.com/roboflow",
    featured: false,
  },

  {
    name: "Clarifai",
    slug: "clarifai",
    logo: "https://logo.clearbit.com/clarifai.com",
    shortDescription: "AI platform for building computer vision and generative AI applications.",
    description:
      "Clarifai provides AI infrastructure and model services for organizations developing visual, language, and generative AI applications.",
    industry: "Computer Vision",
    categories: ["Computer Vision", "Generative AI", "AI Infrastructure"],
    technologies: ["Computer Vision", "NLP", "Generative AI"],
    foundedYear: 2013,
    location: "New York, USA",
    companyType: "AI Platform",
    stage: "Private",
    website: "https://www.clarifai.com",
    linkedin: "https://www.linkedin.com/company/clarifai",
    twitter: "https://x.com/Clarifai",
    github: "https://github.com/Clarifai",
    featured: false,
  },

  {
    name: "AI21 Labs",
    slug: "ai21-labs",
    logo: "https://logo.clearbit.com/ai21.com",
    shortDescription: "AI company developing language models and generative AI applications.",
    description:
      "AI21 Labs develops foundation models and language technologies for enterprise and developer applications.",
    industry: "Artificial Intelligence",
    categories: ["Foundation Models", "Generative AI", "AI Research"],
    technologies: ["LLMs", "NLP", "Generative AI"],
    foundedYear: 2017,
    location: "Tel Aviv, Israel",
    companyType: "AI Company",
    stage: "Private",
    website: "https://www.ai21.com",
    linkedin: "https://www.linkedin.com/company/ai21-labs",
    twitter: "https://x.com/AI21Labs",
    github: "https://github.com/AI21Labs",
    featured: false,
  },

  {
    name: "Sakana AI",
    slug: "sakana-ai",
    logo: "https://logo.clearbit.com/sakana.ai",
    shortDescription: "AI research company exploring efficient and nature-inspired approaches to model development.",
    description:
      "Sakana AI researches new approaches to artificial intelligence inspired by natural systems and collaborative model design.",
    industry: "AI Research",
    categories: ["AI Research", "Foundation Models", "Generative AI"],
    technologies: ["Generative AI", "Model Optimization", "Machine Learning"],
    foundedYear: 2023,
    location: "Tokyo, Japan",
    companyType: "AI Research Company",
    stage: "Private",
    website: "https://sakana.ai",
    linkedin: "https://www.linkedin.com/company/sakana-ai",
    twitter: "https://x.com/SakanaAILabs",
    github: null,
    featured: false,
  },

  {
    name: "Aleph Alpha",
    slug: "aleph-alpha",
    logo: "https://logo.clearbit.com/aleph-alpha.com",
    shortDescription: "European AI company developing foundation models for enterprise applications.",
    description:
      "Aleph Alpha develops generative AI and language model technologies with a focus on enterprise and regulated industries.",
    industry: "Enterprise AI",
    categories: ["Foundation Models", "Enterprise AI", "Generative AI"],
    technologies: ["LLMs", "Multimodal AI", "Generative AI"],
    foundedYear: 2019,
    location: "Heidelberg, Germany",
    companyType: "AI Company",
    stage: "Private",
    website: "https://www.aleph-alpha.com",
    linkedin: "https://www.linkedin.com/company/aleph-alpha",
    twitter: "https://x.com/aleph__alpha",
    github: null,
    featured: false,
  },

  {
    name: "Inflection AI",
    slug: "inflection-ai",
    logo: "https://logo.clearbit.com/inflection.ai",
    shortDescription: "AI company focused on personal and conversational artificial intelligence.",
    description:
      "Inflection AI develops conversational AI systems designed to provide personalized interactions and assistance.",
    industry: "AI Assistants",
    categories: ["Conversational AI", "Generative AI", "AI Assistants"],
    technologies: ["LLMs", "Conversational AI", "NLP"],
    foundedYear: 2022,
    location: "Palo Alto, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://inflection.ai",
    linkedin: "https://www.linkedin.com/company/inflectionai",
    twitter: "https://x.com/inflectionAI",
    github: null,
    featured: false,
  },

  {
    name: "Sierra",
    slug: "sierra",
    logo: "https://logo.clearbit.com/sierra.ai",
    shortDescription: "AI company building autonomous customer service agents for businesses.",
    description:
      "Sierra develops AI agents that help businesses automate customer service conversations and workflows.",
    industry: "Enterprise AI",
    categories: ["AI Agents", "Enterprise AI", "Conversational AI"],
    technologies: ["AI Agents", "LLMs", "Workflow Automation"],
    foundedYear: 2023,
    location: "San Francisco, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://sierra.ai",
    linkedin: "https://www.linkedin.com/company/sierra-ai",
    twitter: "https://x.com/sierra_ai",
    github: null,
    featured: false,
  },

  {
    name: "Typeface",
    slug: "typeface",
    logo: "https://logo.clearbit.com/typeface.ai",
    shortDescription: "Generative AI platform for creating personalized enterprise content.",
    description:
      "Typeface provides generative AI tools that help organizations create branded content across marketing and business workflows.",
    industry: "Enterprise AI",
    categories: ["Generative AI", "Creative AI", "Enterprise AI"],
    technologies: ["Text Generation", "Image Generation", "LLMs"],
    foundedYear: 2022,
    location: "Palo Alto, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://www.typeface.ai",
    linkedin: "https://www.linkedin.com/company/typeface-ai",
    twitter: "https://x.com/typefaceai",
    github: null,
    featured: false,
  },

  {
    name: "Pinecone",
    slug: "pinecone",
    logo: "https://logo.clearbit.com/pinecone.io",
    shortDescription: "Vector database platform built for AI applications and semantic search.",
    description:
      "Pinecone provides vector database infrastructure used for retrieval, semantic search, recommendation, and generative AI applications.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "Developer Tools", "Enterprise AI"],
    technologies: ["Vector Database", "RAG", "Semantic Search"],
    foundedYear: 2019,
    location: "New York, USA",
    companyType: "AI Infrastructure Company",
    stage: "Private",
    website: "https://www.pinecone.io",
    linkedin: "https://www.linkedin.com/company/pinecone-io",
    twitter: "https://x.com/Pinecone",
    github: null,
    featured: false,
  },

  {
    name: "Weights & Biases",
    slug: "weights-and-biases",
    logo: "https://logo.clearbit.com/wandb.ai",
    shortDescription: "Developer platform for tracking, evaluating, and managing machine learning workflows.",
    description:
      "Weights & Biases provides tools for experiment tracking, model evaluation, dataset management, and AI development workflows.",
    industry: "AI Developer Tools",
    categories: ["Developer Tools", "AI Infrastructure", "Machine Learning"],
    technologies: ["MLOps", "Model Evaluation", "Machine Learning"],
    foundedYear: 2017,
    location: "San Francisco, USA",
    companyType: "AI Software Company",
    stage: "Private",
    website: "https://wandb.ai",
    linkedin: "https://www.linkedin.com/company/wandb",
    twitter: "https://x.com/weights_biases",
    github: "https://github.com/wandb",
    featured: false,
  },

  {
    name: "Vercel",
    slug: "vercel",
    logo: "https://logo.clearbit.com/vercel.com",
    shortDescription: "Developer platform providing infrastructure and AI tools for modern applications.",
    description:
      "Vercel provides cloud infrastructure and developer tooling for building, deploying, and scaling modern web and AI applications.",
    industry: "Developer Tools",
    categories: ["Developer Tools", "AI Infrastructure", "Generative AI"],
    technologies: ["Cloud Computing", "AI SDKs", "Serverless"],
    foundedYear: 2015,
    location: "San Francisco, USA",
    companyType: "Technology Company",
    stage: "Private",
    website: "https://vercel.com",
    linkedin: "https://www.linkedin.com/company/vercel",
    twitter: "https://x.com/vercel",
    github: "https://github.com/vercel",
    featured: false,
  },

  {
    name: "Groq",
    slug: "groq-ai",
    logo: "https://logo.clearbit.com/groq.com",
    shortDescription: "AI hardware company building high-performance inference technology.",
    description:
      "Groq develops specialized AI accelerator technology designed to provide fast and efficient inference for machine learning workloads.",
    industry: "AI Hardware",
    categories: ["AI Hardware", "AI Infrastructure", "Developer Tools"],
    technologies: ["AI Accelerators", "Inference", "Machine Learning"],
    foundedYear: 2016,
    location: "Mountain View, USA",
    companyType: "AI Hardware Company",
    stage: "Private",
    website: "https://groq.com",
    linkedin: "https://www.linkedin.com/company/groq",
    twitter: "https://x.com/GroqInc",
    github: null,
    featured: false,
  },

  {
    name: "Lambda",
    slug: "lambda",
    logo: "https://logo.clearbit.com/lambda.ai",
    shortDescription: "AI infrastructure provider offering GPU cloud and machine learning computing.",
    description:
      "Lambda provides accelerated computing infrastructure and GPU cloud services for AI model development and deployment.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "Cloud AI", "AI Hardware"],
    technologies: ["GPU Computing", "Cloud AI", "Model Training"],
    foundedYear: 2012,
    location: "San Francisco, USA",
    companyType: "AI Infrastructure Company",
    stage: "Private",
    website: "https://lambda.ai",
    linkedin: "https://www.linkedin.com/company/lambda-inc",
    twitter: "https://x.com/lambdaAPI",
    github: null,
    featured: false,
  },

  {
    name: "Together Computer",
    slug: "together-computer",
    logo: "https://logo.clearbit.com/together.ai",
    shortDescription: "AI infrastructure company focused on open models and scalable computing.",
    description:
      "Together Computer develops infrastructure for training, fine-tuning, and serving open machine learning models.",
    industry: "AI Infrastructure",
    categories: ["AI Infrastructure", "Foundation Models", "Developer Tools"],
    technologies: ["LLMs", "GPU Computing", "Model Training"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Infrastructure Company",
    stage: "Private",
    website: "https://www.together.ai",
    linkedin: null,
    twitter: "https://x.com/togethercompute",
    github: "https://github.com/togethercomputer",
    featured: false,
  },

  {
    name: "Adept",
    slug: "adept",
    logo: "https://logo.clearbit.com/adept.ai",
    shortDescription: "AI research company developing systems that can interact with software and tools.",
    description:
      "Adept researches AI systems capable of understanding instructions and taking actions across software interfaces.",
    industry: "AI Agents",
    categories: ["AI Agents", "AI Research", "Generative AI"],
    technologies: ["AI Agents", "LLMs", "Computer Interaction"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Research Company",
    stage: "Private",
    website: "https://www.adept.ai",
    linkedin: "https://www.linkedin.com/company/adept-ai",
    twitter: "https://x.com/adeptailabs",
    github: null,
    featured: false,
  },

  {
    name: "Character Technologies",
    slug: "character-technologies",
    logo: "https://logo.clearbit.com/character.ai",
    shortDescription: "Technology company focused on conversational and personalized AI experiences.",
    description:
      "Character Technologies develops conversational AI systems and interactive experiences powered by large language models.",
    industry: "Conversational AI",
    categories: ["Conversational AI", "AI Assistants", "Generative AI"],
    technologies: ["LLMs", "Conversational AI", "NLP"],
    foundedYear: 2021,
    location: "California, USA",
    companyType: "AI Company",
    stage: "Private",
    website: "https://character.ai",
    linkedin: null,
    twitter: "https://x.com/character_ai",
    github: null,
    featured: false,
  },

  {
    name: "Adept AI",
    slug: "adept-ai",
    logo: "https://logo.clearbit.com/adept.ai",
    shortDescription: "AI company researching models that can operate digital interfaces.",
    description:
      "Adept develops AI technology aimed at enabling models to understand software environments and perform useful digital actions.",
    industry: "AI Agents",
    categories: ["AI Agents", "Developer Tools", "AI Research"],
    technologies: ["Computer Interaction", "AI Agents", "LLMs"],
    foundedYear: 2022,
    location: "San Francisco, USA",
    companyType: "AI Research Company",
    stage: "Private",
    website: "https://www.adept.ai",
    linkedin: null,
    twitter: "https://x.com/adeptailabs",
    github: null,
    featured: false,
  },

  {
    name: "Runway Research",
    slug: "runway-research",
    logo: "https://logo.clearbit.com/runwayml.com",
    shortDescription: "AI research organization advancing generative models for visual media.",
    description:
      "Runway's research efforts explore generative models for video, images, and creative production workflows.",
    industry: "Generative Media",
    categories: ["Generative AI", "Video AI", "AI Research"],
    technologies: ["Video Generation", "Diffusion Models", "Computer Vision"],
    foundedYear: 2018,
    location: "New York, USA",
    companyType: "AI Research Organization",
    stage: "Private",
    website: "https://runwayml.com",
    linkedin: null,
    twitter: "https://x.com/runwayml",
    github: null,
    featured: false,
  },

  {
    name: "Character AI Labs",
    slug: "character-ai-labs",
    logo: "https://logo.clearbit.com/character.ai",
    shortDescription: "Research-focused AI organization exploring conversational intelligence.",
    description:
      "Character AI Labs explores language models and conversational systems designed for interactive AI experiences.",
    industry: "AI Research",
    categories: ["AI Research", "Conversational AI", "Generative AI"],
    technologies: ["LLMs", "NLP", "Conversational AI"],
    foundedYear: 2021,
    location: "California, USA",
    companyType: "AI Research Organization",
    stage: "Private",
    website: "https://character.ai",
    linkedin: null,
    twitter: "https://x.com/character_ai",
    github: null,
    featured: false,
  },
]

async function main() {
  console.log('Seeding custom companies list...')
  for (const c of aiCompanies) {
    try {
      await prisma.aiCompany.upsert({
        where: { slug: c.slug },
        update: {
          name: c.name,
          logo: c.logo || '',
          shortDescription: c.shortDescription,
          description: c.description,
          industry: c.industry,
          categories: c.categories.join(','),
          technologies: c.technologies.join(','),
          foundedYear: c.foundedYear,
          location: c.location,
          companyType: c.companyType,
          stage: c.stage,
          website: c.website,
          linkedin: c.linkedin,
          twitter: c.twitter,
          github: c.github,
          featured: c.featured
        },
        create: {
          name: c.name,
          slug: c.slug,
          logo: c.logo || '',
          shortDescription: c.shortDescription,
          description: c.description,
          industry: c.industry,
          categories: c.categories.join(','),
          technologies: c.technologies.join(','),
          foundedYear: c.foundedYear,
          location: c.location,
          companyType: c.companyType,
          stage: c.stage,
          website: c.website,
          linkedin: c.linkedin,
          twitter: c.twitter,
          github: c.github,
          featured: c.featured
        },
      })
      console.log(`Upserted custom company: ${c.name}`)
    } catch (e) {
      console.error(`Error upserting ${c.slug}`, e)
    }
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
